# Generated by Django 4.0.4 on 2022-05-28 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_name', models.CharField(max_length=30, verbose_name='Название')),
                ('pump_addr', models.CharField(max_length=15, verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='Valley',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valley_name', models.CharField(max_length=30, verbose_name='Название')),
                ('valley_addr', models.CharField(max_length=15, verbose_name='Адрес')),
                ('valley_rele', models.SmallIntegerField(default=0)),
                ('valley_pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valley', to='valley.pump')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_run', models.BooleanField(default=False)),
                ('status_ctrl', models.BooleanField(default=False)),
                ('status_dir', models.CharField(choices=[('N', 'No'), ('F', 'Forvard'), ('R', 'Revers')], default='N', max_length=1)),
                ('status_wat', models.BooleanField(default=False)),
                ('status_sis', models.BooleanField(default=False)),
                ('status_valley', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status', serialize=False, to='valley.valley')),
            ],
        ),
    ]
