# Generated by Django 4.0.4 on 2022-05-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valley', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vall_Status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('run', models.BooleanField()),
                ('ctrl', models.BooleanField()),
                ('fail', models.BooleanField()),
                ('dir', models.IntegerField(max_length=1)),
                ('wat', models.BooleanField()),
                ('sis', models.BooleanField()),
            ],
        ),
    ]
