# Generated by Django 4.0.4 on 2022-05-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valley', '0002_vall_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vall_status',
            name='dir',
            field=models.CharField(max_length=1),
        ),
    ]
