# Generated by Django 4.0.4 on 2022-05-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valley', '0003_alter_valley_valley_duet_alter_valley_valley_rele'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='status_fail',
            field=models.BooleanField(default=False),
        ),
    ]
