# Generated by Django 4.0.4 on 2022-05-29 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valley', '0004_status_status_fail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pump',
            options={'ordering': ['pk'], 'verbose_name': 'Насос', 'verbose_name_plural': 'Насосы'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['pk'], 'verbose_name': 'Состояние системы', 'verbose_name_plural': 'Состояние систем'},
        ),
        migrations.AlterModelOptions(
            name='valley',
            options={'ordering': ['pk'], 'verbose_name': 'Система полива', 'verbose_name_plural': 'Системы полива'},
        ),
        migrations.AlterField(
            model_name='status',
            name='status_ctrl',
            field=models.BooleanField(default=False, verbose_name='Управление'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_dir',
            field=models.CharField(choices=[('N', 'No'), ('F', 'Forvard'), ('R', 'Revers')], default='N', max_length=1, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_fail',
            field=models.BooleanField(default=False, verbose_name='Авария'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_run',
            field=models.BooleanField(default=False, verbose_name='Запущена'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_sis',
            field=models.BooleanField(default=False, verbose_name='АвтоСтоп'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_valley',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='status', serialize=False, to='valley.valley', verbose_name='Система'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status_wat',
            field=models.BooleanField(default=False, verbose_name='Вода'),
        ),
        migrations.AlterField(
            model_name='valley',
            name='valley_duet',
            field=models.SmallIntegerField(default=0, verbose_name='Связка'),
        ),
        migrations.AlterField(
            model_name='valley',
            name='valley_pump',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valley', to='valley.pump', verbose_name='Насос'),
        ),
        migrations.AlterField(
            model_name='valley',
            name='valley_rele',
            field=models.SmallIntegerField(default=1, verbose_name='Реле'),
        ),
    ]
