# Generated by Django 4.0.4 on 2022-05-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valley', '0005_remove_pump_duet_valley_duet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valley',
            name='duet',
            field=models.IntegerField(default=0),
        ),
    ]
