# Generated by Django 4.0.4 on 2022-05-27 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valley', '0006_alter_valley_duet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vall_status',
            name='id',
        ),
        migrations.AddField(
            model_name='vall_status',
            name='valley',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='valley.valley'),
            preserve_default=False,
        ),
    ]
