# Generated by Django 4.0.4 on 2022-05-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valley', '0006_alter_status_status_dir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['pk'], 'verbose_name': 'Состояние системы', 'verbose_name_plural': 'Состояния систем'},
        ),
    ]
