# Generated by Django 4.0.4 on 2022-06-02 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valley', '0007_alter_status_options'),
        ('valley', '0007_remove_vall_status_id_vall_status_valley'),
    ]

    operations = [
    ]
