# Generated by Django 4.0.4 on 2022-06-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valley', '0008_merge_20220602_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valley',
            name='duet',
        ),
        migrations.AddField(
            model_name='status',
            name='status_valve1',
            field=models.BooleanField(default=False, verbose_name='Задвижка 1'),
        ),
        migrations.AddField(
            model_name='status',
            name='status_valve2',
            field=models.BooleanField(default=False, verbose_name='Задвижка 2'),
        ),
        migrations.DeleteModel(
            name='Vall_Status',
        ),
    ]
