# Generated by Django 4.0.5 on 2022-06-08 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_alter_videosrv_options_and_more'),
        ('valley', '0010_valley_valley_camera_valley_valley_videosrv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valley',
            name='valley_camera',
            field=models.CharField(max_length=8, verbose_name='Камера'),
        ),
        migrations.AlterField(
            model_name='valley',
            name='valley_videosrv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valley_cam', to='surveillance.videosrv', verbose_name='Видео сервер'),
        ),
    ]
