# Generated by Django 4.0.5 on 2022-06-10 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0003_videosrv_videosrv_http_videosrv_videosrv_video'),
        ('valley', '0011_alter_valley_valley_camera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valley',
            name='valley_camera',
            field=models.CharField(max_length=8, null=True, verbose_name='Камера'),
        ),
        migrations.AlterField(
            model_name='valley',
            name='valley_videosrv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='valley_cam', to='surveillance.videosrv', verbose_name='Видео сервер'),
        ),
    ]
