# Generated by Django 4.0.5 on 2022-06-18 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('valley', '0013_journal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Журналы', 'verbose_name_plural': 'Журнал'},
        ),
        migrations.AddField(
            model_name='journal',
            name='jornal_act',
            field=models.CharField(choices=[('R', 'Запуск'), ('S', 'Остановка')], default='S', max_length=1, verbose_name='Действия'),
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_valley',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='valley.valley', verbose_name='Система'),
        ),
    ]
