# Generated by Django 4.0.5 on 2022-06-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valley', '0015_rename_jornal_act_journal_journal_act_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jdetails',
            name='jdetails_valve1',
        ),
        migrations.RemoveField(
            model_name='jdetails',
            name='jdetails_valve2',
        ),
    ]
