# Generated by Django 4.0.5 on 2022-06-22 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valley', '0016_remove_jdetails_jdetails_valve1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JDetails',
        ),
    ]
