# Generated by Django 4.0.5 on 2022-06-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valley', '0017_delete_jdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='journal_dir',
            field=models.CharField(choices=[('N', '-'), ('F', 'Вперёд'), ('R', 'Назад')], default='N', max_length=1, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_sis',
            field=models.BooleanField(default=False, verbose_name='АвтоСтоп'),
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_user',
            field=models.CharField(default='admin', max_length=20, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_wat',
            field=models.BooleanField(default=False, verbose_name='Вода'),
        ),
    ]
