# Generated by Django 4.0.5 on 2022-06-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valley', '0018_journal_journal_dir_journal_journal_sis_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'verbose_name': 'Журнал', 'verbose_name_plural': 'Журналы'},
        ),
    ]
