# Generated by Django 4.0.5 on 2022-06-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valley', '0020_alter_valley_valley_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valley',
            name='valley_camera',
            field=models.CharField(max_length=100, null=True, verbose_name='Камера'),
        ),
    ]
