# Generated by Django 4.0.6 on 2022-07-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valley', '0022_journal_journal_depth_journal_journal_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_depth',
            field=models.FloatField(default=False, verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_hours',
            field=models.FloatField(default=False, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_perc',
            field=models.FloatField(default=False, verbose_name='Скорость'),
        ),
    ]
