# Generated by Django 4.0.4 on 2022-05-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videosrv',
            options={'ordering': ['pk'], 'verbose_name': 'Видео сервер', 'verbose_name_plural': 'Видео серверы'},
        ),
        migrations.AlterField(
            model_name='videosrv',
            name='videosrv_password',
            field=models.CharField(max_length=30, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='videosrv',
            name='videosrv_user',
            field=models.CharField(max_length=15, verbose_name='Пользователь'),
        ),
    ]
