# Generated by Django 4.0.5 on 2022-06-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0003_videosrv_videosrv_http_videosrv_videosrv_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosrv',
            name='videosrv_http',
            field=models.IntegerField(null=True, verbose_name='Порт HTTP'),
        ),
        migrations.AlterField(
            model_name='videosrv',
            name='videosrv_video',
            field=models.IntegerField(null=True, verbose_name='Порт видео'),
        ),
    ]
